### ISSUE TITLE
doesnt detect the gestures or even hand when placed in the box

### ISSUE THREAD

**Issue by SANSKRUTI04** [priyanka-maz/sign-language-detection#1]
the recognition/detection model is detecting the gestures or even hand. please guide
![image](https://github.com/priyanka-maz/sign-language-detection/assets/103131134/ba4a3a35-b3e9-4e8c-b35a-889442bf21f4)

**Comment by priyanka-maz** [comment]
Is the console throwing any error? Have you installed all the given
requirements? Since, it is working on my end.

**Comment by SANSKRUTI04** [comment]
no the console is not throwing any error also we have imported all the necessary packages......when we type words in the console the speech output is working
only the detection is not working as shown in the picture..... could you please check whether you have updated any part of the code after creating the repository on the github

**Comment by SANSKRUTI04** [comment]
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO) getting this error on my terminal

**Comment by priyanka-maz** [comment]
Then you need to install another version of Socketio, I think your system
has a newer version.

**Comment by SANSKRUTI04** [comment]
the issue has been resolved..thank you soo much

**Comment by SANSKRUTI04** [comment]
which algorithm you have used for hashing the file because we are working on Indian sign language dataset so we are not able figure out the algorithm could you please explain a bit

**Comment by priyanka-maz** [comment]
First gz and then tar

**Comment by SANSKRUTI04** [comment]
okayy

**Comment by SANSKRUTI04** [comment]
soo basically we have to convert the dataset file first into tar.gz??

im asking about this code
DATASET_DIR = pathlib.Path(
    tf.keras.utils.get_file(
        fname="American_Sign_Language_Letters_Multiclass.tar",
        origin="file:./datasets/American_Sign_Language_Letters_Multiclass.tar.gz",
        file_hash="f76def78d7efbfd23ca9340a58fce1026dca21500efa2764caa064fa843fdf23",
        extract=True,

how you have got that hash value??

**Comment by pganguli** [comment]
> soo basically we have to convert the dataset file first into tar.gz??
> 
> im asking about this code DATASET_DIR = pathlib.Path( tf.keras.utils.get_file( fname="American_Sign_Language_Letters_Multiclass.tar", origin="file:./datasets/American_Sign_Language_Letters_Multiclass.tar.gz", file_hash="f76def78d7efbfd23ca9340a58fce1026dca21500efa2764caa064fa843fdf23", extract=True,
> 
> how you have got that hash value??

The dataset format is the same as the one used in the official documentation found [here](https://www.tensorflow.org/tutorials/images/classification#download_and_explore_the_dataset), along with its corresponding Jupyter Notebook [here](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/classification.ipynb). You can perhaps download our dataset (or the one in the tutorial) and explore it by decompressing it using 7-zip (on Windows) or on Linux with the following command:
```sh
tar -xvf dataset.tar.gz
```

Similarly, for creating your own dataset, put directories named with the labels for classification inside a directory named with the dataset's name, and put each class's image files in the corresponding subdirectory.

It should look like:
```
Dataset
├── class_A
│   ├── img0.jpg
│   ├── img1.jpg
│   ├── img2.jpg
├── class_B
│   ├── img0.jpg
│   ├── img1.jpg
│   ├── img2.jpg
...
```

You can then compress the `Dataset` folder using 7-zip (compress as .tar, followed by compressing the .tar as .gz or gzip) or on Linux with the following command:
```sh
tar -cvaf Dataset.tar.gz Dataset/
```

The `file_hash` parameter is purely optional, and the reason I used it in our project is to simply prevent accidental loading of any WIP datasets I had created. It's good for versioning and safety purposes, as the loading fails if the hash value doesn't match. As you can see from the documentation of [tf.keras.utils.get_file](https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file), it is just a md5 or sha256 hash. On Linux, you can obtain the hash as:
```sh
sha256sum Dataset.tar.gz
# or
md5sum Dataset.tar.gz # try to use sha256 hashes, since md5 is deprecated
```

**Comment by SANSKRUTI04** [comment]
okayy thank youu

but im getting this error after adding my path in the dataset dir
DATASET_DIR = pathlib.Path(
    tf.keras.utils.get_file(
        fname="C:/Users/sansk/OneDrive/Documents/sign-language-detection-main/sign-language-detection-main/Indian_Sign_Language.tar",
        origin="C:/Users/sansk/OneDrive/Documents/sign-language-detection-main/sign-language-detection-main/Indian_Sign_Language.tar.gz",
        #file_hash="f198894b480b9336d3643c1e7faa3f3dec1d8af84decd789b4dd20b960162cad",
        extract=True,
    )
).with_suffix("")

error :-

Downloading data from C:/Users/sansk/OneDrive/Documents/sign-language-detection-main/sign-language-detection-main/Indian_Sign_Language.tar.gz
Traceback (most recent call last):
  File "C:\Users\sansk\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\data_utils.py", line 347, in get_file
    urlretrieve(origin, fpath, DLProgbar())
  File "C:\Users\sansk\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\data_utils.py", line 85, in urlretrieve
    response = urlopen(url, data)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\urllib\request.py", line 541, in _open
    return self._call_chain(self.handle_open, 'unknown',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\urllib\request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: c>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sansk\OneDrive\Documents\sign-language-detection-main\sign-language-detection-main\train.py", line 10, in <module>
    tf.keras.utils.get_file(
  File "C:\Users\sansk\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\data_utils.py", line 351, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on C:/Users/sansk/OneDrive/Documents/sign-language-detection-main/sign-language-detection-main/Indian_Sign_Language.tar.gz: None -- unknown url type: c

**Comment by pganguli** [comment]
> okayy thank youu
> 
> but im getting this error after adding my path in the dataset dir DATASET_DIR = pathlib.Path( tf.keras.utils.get_file( fname="C:/Users/sansk/OneDrive/Documents/sign-language-detection-main/sign-language-detection-main/Indian_Sign_Language.tar", origin="C:/Users/sansk/OneDrive/Documents/sign-language-detection-main/sign-language-detection-main/Indian_Sign_Language.tar.gz", #file_hash="f198894b480b9336d3643c1e7faa3f3dec1d8af84decd789b4dd20b960162cad", extract=True, ) ).with_suffix("")
> 
> error :-
> 
> Downloading data from C:/Users/sansk/OneDrive/Documents/sign-language-detection-main/sign-language-detection-main/Indian_Sign_Language.tar.gz Traceback (most recent call last): File "C:\Users\sansk\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\data_utils.py", line 347, in get_file urlretrieve(origin, fpath, DLProgbar()) File "C:\Users\sansk\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\data_utils.py", line 85, in urlretrieve response = urlopen(url, data) ^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python311\Lib\urllib\request.py", line 216, in urlopen return opener.open(url, data, timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python311\Lib\urllib\request.py", line 519, in open response = self._open(req, data) ^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python311\Lib\urllib\request.py", line 541, in _open return self._call_chain(self.handle_open, 'unknown', ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python311\Lib\urllib\request.py", line 496, in _call_chain result = func(*args) ^^^^^^^^^^^ File "C:\Program Files\Python311\Lib\urllib\request.py", line 1419, in unknown_open raise URLError('unknown url type: %s' % type) urllib.error.URLError:
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "c:\Users\sansk\OneDrive\Documents\sign-language-detection-main\sign-language-detection-main\train.py", line 10, in tf.keras.utils.get_file( File "C:\Users\sansk\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\data_utils.py", line 351, in get_file raise Exception(error_msg.format(origin, e.errno, e.reason)) Exception: URL fetch failure on C:/Users/sansk/OneDrive/Documents/sign-language-detection-main/sign-language-detection-main/Indian_Sign_Language.tar.gz: None -- unknown url type: c

I believe that the issue here is the way the function treats slashes in Windows file paths. These functions were designed keeping Linux file paths in mind, so it works flawlessly on my end here.

@priyanka-maz ran the same code, with the paths modified for Windows. Perhaps you can help us here.

**Comment by SANSKRUTI04** [comment]
u mean i need to keep it with backward slashes??

**Comment by priyanka-maz** [comment]
Yes, if you’re training on windows, that is

**Comment by SANSKRUTI04** [comment]
i didnt get it.. could you please explain?? @priyanka-maz

**Comment by priyanka-maz** [comment]
On windows, the path is defined using \

**Comment by SANSKRUTI04** [comment]
yaa but when i put \ this slash i get unicode error soo i have to put this / slash then only it runs

**Comment by priyanka-maz** [comment]
To remove Unicode error, you need to define it as
r”path\to\dir”

**Comment by SANSKRUTI04** [comment]
@priyanka-maz actually the problem is not with the unicode the problem we are getting is this....i think that ur fetching the tf.keras.utils.get_file from internet right?? we have our dataset in our system locally so its getting fetched
code :- 
DATASET_DIR = pathlib.Path(
tf.keras.utils.get_file(
fname="C:/Users/sansk/OneDrive/Documents/sign-language-detection-main/sign-language-detection-main/Indian_Sign_Language.tar",
origin="C:/Users/sansk/OneDrive/Documents/sign-language-detection-main/sign-language-detection-main/Indian_Sign_Language.tar.gz",
#file_hash="f198894b480b9336d3643c1e7faa3f3dec1d8af84decd789b4dd20b960162cad",
extract=True,
)
).with_suffix("")

error :-

Downloading data from C:/Users/sansk/OneDrive/Documents/sign-language-detection-main/sign-language-detection-main/Indian_Sign_Language.tar.gz
Traceback (most recent call last):
File "C:\Users\sansk\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\data_utils.py", line 347, in get_file
urlretrieve(origin, fpath, DLProgbar())
File "C:\Users\sansk\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\data_utils.py", line 85, in urlretrieve
response = urlopen(url, data)
^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\urllib\request.py", line 216, in urlopen
return opener.open(url, data, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\urllib\request.py", line 519, in open
response = self._open(req, data)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\urllib\request.py", line 541, in _open
return self._call_chain(self.handle_open, 'unknown',
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\urllib\request.py", line 496, in _call_chain
result = func(*args)
^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\urllib\request.py", line 1419, in unknown_open
raise URLError('unknown url type: %s' % type)
urllib.error.URLError:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:\Users\sansk\OneDrive\Documents\sign-language-detection-main\sign-language-detection-main\train.py", line 10, in
tf.keras.utils.get_file(
File "C:\Users\sansk\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\data_utils.py", line 351, in get_file
raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on C:/Users/sansk/OneDrive/Documents/sign-language-detection-main/sign-language-detection-main/Indian_Sign_Language.tar.gz: None -- unknown url type: c

**Comment by priyanka-maz** [comment]
No, we too have our files locally. The only difference is that we had
developed on a Linux system.
So you need to adapt the code according to windows since that is the system
you are using.

**Comment by SANSKRUTI04** [comment]
okayy!!! @priyanka-maz  soo the main problem is with the fetching the files it is giving error in that dataset dir

**Comment by SANSKRUTI04** [comment]
@priyanka-maz how did you create model files under model section

**Comment by pganguli** [comment]
> @priyanka-maz how did you create model files under model section

This question is out of scope of this issue; please raise another one if you need further assistance with this.

In general, study the code of [train.py](https://github.com/priyanka-maz/sign-language-detection/blob/main/train.py) carefully first. I have linked the relevant lines of code, that save the trained model, below:

https://github.com/priyanka-maz/sign-language-detection/blob/4f10f55f9e18637432da6c31d55ffb00fc88d650/train.py#L18-L19

https://github.com/priyanka-maz/sign-language-detection/blob/4f10f55f9e18637432da6c31d55ffb00fc88d650/train.py#L196-L209

https://github.com/priyanka-maz/sign-language-detection/blob/4f10f55f9e18637432da6c31d55ffb00fc88d650/train.py#L304
