### ISSUE TITLE
 how have you created these files??

### ISSUE THREAD

**Issue by SANSKRUTI04** [priyanka-maz/sign-language-detection#2]
![image](https://github.com/priyanka-maz/sign-language-detection/assets/103131134/07bdbeba-8019-40e7-b1e8-7bdef131ccde)

**Comment by pganguli** [comment]
In general, study the code of [train.py](https://github.com/priyanka-maz/sign-language-detection/blob/main/train.py) carefully first. I have linked the relevant lines of code, that save the trained model, below:

https://github.com/priyanka-maz/sign-language-detection/blob/4f10f55f9e18637432da6c31d55ffb00fc88d650/train.py#L18-L19

https://github.com/priyanka-maz/sign-language-detection/blob/4f10f55f9e18637432da6c31d55ffb00fc88d650/train.py#L196-L209

https://github.com/priyanka-maz/sign-language-detection/blob/4f10f55f9e18637432da6c31d55ffb00fc88d650/train.py#L304

_Originally posted by @pganguli in https://github.com/priyanka-maz/sign-language-detection/issues/1#issuecomment-1806169766_

**Comment by pganguli** [comment]
The tflite models were created using train.py, with different base models (such as MobileNet and EfficientNet).

The training output text files are simply dumps of the console output obtained during the respective executions of train.py.

**Comment by SANSKRUTI04** [comment]
does the dimension of the image affects the sign detection? and if so which part of the code to be changed
please guide!

**Comment by priyanka-maz** [comment]
Please read up about how CNNs work for computer vision and the mathematics
around it. Otherwise it will be hard to understand. That will answer
your question.
